### Register a new user (normal user)
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "Tee",
  "password": "Tee@1908",
  "email": "Tee@example.com",
  "role": "ADMIN"
 
}

### Login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "adminuser",
  "password": "Ncane@1908"
}


### Create a task for adminuser (assigns task)
POST http://127.0.0.1:8000/api/tasks/
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "title": "Testing report",
  "description": "Complete the finance report for Q2",
  "status": "PENDING",
  "due_date": "2025-06-01",
  "assigned_to": "1"
}


### Get all tasks
GET http://127.0.0.1:8000/api/tasks/
Authorization: Bearer <access_token>

### Get my tasks
GET http://127.0.0.1:8000/api/my-tasks/
Authorization: Bearer <access_token>

### Delete a task
DELETE http://127.0.0.1:8000/api/tasks/4/
Authorization: Bearer <access_token>

### Refresh token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "<refresh_token>"
}