# Generated by Django 5.2 on 2025-05-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managerApp", "0002_remove_task_completed_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed_date",
        ),
    ]
